/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query receipts with pagination */
        get: operations["queryReceipts"];
        put?: never;
        /** Generate a receipt PDF */
        post: operations["createReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{sessionId}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get signed URL for a receipt PDF */
        get: operations["getReceiptUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** Format: date-time */
            timestamp: string;
        };
        CreateReceiptRequest: {
            /**
             * @description Unique charging session ID
             * @example session-12345
             */
            session_id: string;
            /**
             * @description Customer/consumer ID
             * @example consumer-john-doe
             */
            consumer_id: string;
            /**
             * @description Reference to a pre-registered company (e.g., 'voltcharge', 'greencharge', 'rapidev'). When provided, company info is auto-populated.
             * @example voltcharge
             */
            company_ref?: string;
            receipt: components["schemas"]["ReceiptData"];
        };
        /** @description Receipt data. If company_ref is provided in the request, company fields (company_name, company_tagline, etc.) are optional. */
        ReceiptData: {
            /** @example VoltCharge UK */
            company_name?: string;
            /** @example Fast & Clean Energy */
            company_tagline?: string;
            /**
             * @description SVG markup or base64 data URI for company logo
             * @example <svg>...</svg>
             */
            company_logo_svg?: string;
            /** @example www.voltcharge.co.uk */
            company_website?: string;
            /** @example support@voltcharge.co.uk */
            support_email?: string;
            /** @example 0800-VOLTCHG */
            support_phone?: string;
            /** @example EVC-2025-41823 */
            receipt_number: string;
            /** @example 24 December 2025 */
            receipt_date: string;
            /** @example London Plaza - Station #12 */
            station_name: string;
            /** @example 456 Electric Avenue, London, EC1A 1BB */
            station_address: string;
            /** @example CCS Type 2 */
            connector_type: string;
            /** @example 150 kW DC Fast Charger */
            charger_power: string;
            /** @example 14:32 */
            session_start_time: string;
            /** @example 15:17 */
            session_end_time: string;
            /** @example 45 */
            session_duration: string;
            /** @example 42.8 */
            energy_delivered: string;
            /** @example 22 */
            battery_start: string;
            /** @example 87 */
            battery_end: string;
            /** @example 118 */
            avg_charging_speed: string;
            /** @example Tesla */
            vehicle_make: string;
            /** @example Model 3 Long Range */
            vehicle_model: string;
            /** @example •••••••••1234XYZ */
            vehicle_vin: string;
            /** @example £0.28 */
            energy_rate: string;
            /** @example £11.98 */
            energy_cost: string;
            /** @example £0.80 */
            session_fee: string;
            /** @example 0 */
            idle_minutes: string;
            /** @example £0.32 */
            idle_rate: string;
            /** @example £0.00 */
            idle_fee: string;
            /** @example £12.78 */
            subtotal: string;
            /** @example 20% */
            vat_rate: string;
            /** @example £2.56 */
            vat_amount: string;
            /** @example Member Discount */
            discount_label?: string;
            /** @example 10% */
            discount_percent?: string;
            /** @example £1.28 */
            discount_amount?: string;
            /** @example £14.06 */
            total_amount: string;
            /** @example Visa */
            card_brand: string;
            /** @example 4582 */
            card_last_four: string;
            /** @example Paid */
            payment_status: string;
        };
        CreateReceiptResponse: {
            success: boolean;
            data: {
                session_id: string;
                pdf_key: string;
                metadata_key: string;
                index_key: string;
                /** @description Pre-signed URL to download the PDF (valid for 1 hour) */
                signed_url?: string;
            };
        };
        QueryReceiptsResponse: {
            success: boolean;
            data: {
                records: components["schemas"]["ReceiptMetadata"][];
                pagination: {
                    /** @description Total number of matching records */
                    total_count: number;
                    /** @description Number of records per page */
                    page_size: number;
                    /** @description Whether more results are available */
                    has_more: boolean;
                    /** @description Cursor for fetching next page */
                    next_cursor?: string;
                };
                /** @description List of dates that were scanned (YYYY-MM-DD) */
                scanned_dates: string[];
            };
        };
        ReceiptMetadata: {
            session_id: string;
            consumer_id: string;
            receipt_number: string;
            /** Format: date */
            payment_date: string;
            card_last_four: string;
            amount: string;
            pdf_key: string;
            metadata_key: string;
            /** Format: date-time */
            created_at: string;
        };
        SignedUrlResponse: {
            success: boolean;
            data: {
                url: string;
                /** @description Seconds until URL expires */
                expires_in: number;
            };
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    queryReceipts: {
        parameters: {
            query?: {
                /** @description Filter by session ID (exact match) */
                session_id?: string;
                /** @description Filter by consumer ID (exact match) */
                consumer_id?: string;
                /** @description Filter by last 4 digits of payment card */
                card_last_four?: string;
                /** @description Filter by receipt number (exact match) */
                receipt_number?: string;
                /** @description Start date for query range (YYYY-MM-DD) */
                date_from?: string;
                /** @description End date for query range (YYYY-MM-DD) */
                date_to?: string;
                /** @description Minimum amount filter */
                amount_min?: number;
                /** @description Maximum amount filter */
                amount_max?: number;
                /** @description Maximum number of results to return (default 50, max 100) */
                limit?: number;
                /** @description Cursor for pagination (from previous response) */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query results with pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryReceiptsResponse"];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReceiptRequest"];
            };
        };
        responses: {
            /** @description Receipt created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateReceiptResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getReceiptUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed URL generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrlResponse"];
                };
            };
            /** @description Receipt not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
